# Generated by Django 2.1.3 on 2018-11-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='post',
            name='date_toshow',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
