# Generated by Django 2.1.3 on 2018-11-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181124_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_toshow',
        ),
    ]
