# Generated by Django 2.1.3 on 2018-12-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
    ]
